version: '3.8'

services:
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - BANKROLL=100
      - AUTO_REINVEST=true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped